# Generated by Django 3.2.4 on 2021-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.IntegerField(null=True),
        ),
    ]
