# Generated by Django 3.2.4 on 2021-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.IntegerField(null=True, verbose_name='confirmation code'),
        ),
    ]
