# Generated by Django 3.2 on 2021-06-04 22:13

import django.core.validators
from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.FloatField(verbose_name=django.utils.translation.gettext),
        ),
        migrations.AlterField(
            model_name='campaignattachment',
            name='file',
            field=models.FileField(upload_to='attachment', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4'])], verbose_name='file'),
        ),
    ]
