# Generated by Django 3.2.4 on 2021-06-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
